// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace MovieConcept
{
    public partial class imdbOriginalContext : DbContext
    {
        public imdbOriginalContext()
        {
        }

        public imdbOriginalContext(DbContextOptions<imdbOriginalContext> options)
            : base(options)
        {
        }

        public virtual DbSet<NameBasics> NameBasics { get; set; }
        public virtual DbSet<TitleAkas> TitleAkas { get; set; }
        public virtual DbSet<TitleBasics> TitleBasics { get; set; }
        public virtual DbSet<TitlePrincipals> TitlePrincipals { get; set; }
        public virtual DbSet<TitleRatings> TitleRatings { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            //modelBuilder.Entity<NameBasics>(entity =>
            //{
            //    entity.HasKey(e => e.Nconst)
            //        .HasName("PK_name.basicss");
            //});

            //modelBuilder.Entity<TitleAkas>(entity =>
            //{
            //    entity.HasOne(d => d.TitleNavigation)
            //        .WithMany()
            //        .HasForeignKey(d => d.TitleId)
            //        .HasConstraintName("FK_title.akas_title.basics");
            //});

            modelBuilder.Entity<TitlePrincipals>().HasKey(tp => new { tp.Tconstt, tp.Nconst });
                    

            //    entity.HasOne(d => d.TconstNavigation)
            //        .WithMany()
            //        .HasForeignKey(d => d.Tconst)
            //        .OnDelete(DeleteBehavior.ClientSetNull)
            //        .HasConstraintName("FK_title.principals_title.basics");
            //});

            //modelBuilder.Entity<TitleRatings>(entity =>
            //{
            //    entity.HasOne(d => d.TconstNavigation)
            //        .WithOne(p => p.TitleRatings)
            //        .HasForeignKey<TitleRatings>(d => d.Tconst)
            //        .OnDelete(DeleteBehavior.ClientSetNull)
            //        .HasConstraintName("FK_title.ratings_title.basics");
            //});

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}