// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace MovieConcept
{
    [Table("title.akas")]
    public partial class TitleAkas
    {
        [Key, ForeignKey("TitleBasics")]
        [Column("titleId")]
        [StringLength(50)]
        [JsonIgnore]
        public string TitleId { get; set; }

        [Column("ordering")]
        public byte? Ordering { get; set; }
        [Column("title")]
        public string Title { get; set; }
        [Column("region")]
        public string Region { get; set; }

        [JsonIgnore]
        
        public virtual TitleBasics TitleBasics { get; set; }
    }
}